### ISSUE TITLE
Request sent in Test scripts overrides Original requests.

### ISSUE THREAD

**Issue by parin921996** [MarcosEllys/newman-html-report-template-verbose#1]
Newman version : 3.9.3
Exported Postman Template Version : 2.1

I need to block execution of script till certain conditions are met which i check by sending request using pm.sendRequest() .
All this request overrides the original request when report gets generated. 

Steps to reproduce:

1. Create a postman request 
2. add script `pm.sendRequest("http://www.example.com/", function (err, res) {
         //add more code if you want
response_code = res.code;
        });`
3. export and generate HTML report.
4. In the report instead of your original request you will see "http://www.example.com/" request and according reposnse.

**Comment by MarcosEllys** [comment]
Okay, i will verify if this happened with my template or is a bug with newman

**Comment by MarcosEllys** [comment]
I'm so sorry, there are a issue opened for this problem, at moment newman report html don't support  pm.sendRequest and the time of development knew this, you can see the issue here [Newman HTML report error with pm.sendRequest](https://github.com/postmanlabs/newman/issues/1303)

**Comment by parin921996** [comment]
Thank you for update..
