### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by bhanupinninti** [MarcosEllys/newman-html-report-template-verbose#2]
Hi,

I am using your HBS file in my project and able to generate the test report. I am facing an issue while clicking on the API name to view the details. It is not giving details page, can you please help what I am missing here.

![image](https://user-images.githubusercontent.com/38074414/40464834-e6bc4cf2-5f60-11e8-9fb2-6a72f82f9f0e.png)

**Comment by bhanupinninti** [comment]
I tried in IE, Chrome and Firefox..same behavior

**Comment by MarcosEllys** [comment]
Thanks i will verify

**Comment by bhanupinninti** [comment]
Any update Marcos???

**Comment by MarcosEllys** [comment]
Yeah, I made some tests here and works perfectly,i don't understand this behavior with your tests, my template uses bootstrap framework likes default template.

Could you run your tests with default template, and if collapse test don't works there are some error with browsers.

The command to run newman with default template is:
newman run -e my.environment.json --reporters cli,html --reporter-html-export nice_report.html my.collection.json

**Comment by bhanupinninti** [comment]
Thanks. Do i need to install bootstrap?

**Comment by MarcosEllys** [comment]
No, bootstrap is already include in the template :)

**Comment by bhanupinninti** [comment]
Mate I tried running by default template and collapsible pannel worked perfectly, when I switched to yours its again broken.

**Comment by MarcosEllys** [comment]
Hey man, i made a few changes, do you could test now with my template?

**Comment by bhanupinninti** [comment]
No my friend..all links and clicks are not working.. :(..not sure what setting at my end casuing this..

![image](https://user-images.githubusercontent.com/38074414/40632595-260da0f8-632c-11e8-8fe1-41f8e772a0bc.png)

**Comment by MarcosEllys** [comment]
Ok, well, it's a bit funny but i cannot understand this behavior, then could you to make more one test?

Please, verify if this collapse code work's well -> https://codepen.io/HelloLeeChan/pen/gaqbrq

If it works i can change my template and help you :)

**Comment by bhanupinninti** [comment]
Yes the collapsible panels in the link are working for me. Appreciate if u can align ur template according to this code.

![image](https://user-images.githubusercontent.com/38074414/40691367-da119b28-63ee-11e8-8d3a-691d6bcad236.png)

**Comment by bhanupinninti** [comment]
Hey, any update. any reason why it is closed now?

**Comment by MarcosEllys** [comment]
Tonight I added the aria-expanded property, which was the only property that was not present

**Comment by bhanupinninti** [comment]
Do u want me to try template u have?

**Comment by bhanupinninti** [comment]
Finally worked mae. thank you very much for your support..
