### ISSUE TITLE
In report, "Show Failures" does not show Failed Use cases only.

### ISSUE THREAD

**Issue by shisapian** [MarcosEllys/newman-html-report-template-verbose#3]
It's a nice report template.

1) "Show errors" does not show only error tests. It shows all the test names. ( fyi, I do not have any errors in my collection)

2) There should be an  Aggregated report column ( Total no of tests, total failures, total, success). Once you click on number , you should see the error tests.)

**Comment by MarcosEllys** [comment]
Yeah, you're right.

1 - "Show erros" does not show now (I made this change today).

2- For now i can't imagine one section with report aggregation (Total no of tests, total failures, total success), however there are three buttons wich have actions to show/hide requests success/error.

**Comment by shisapian** [comment]
Thanks for getting this done. 
But in any report its very important to show the total no of tests, success and failures links and then drilling down further details.

**Comment by MarcosEllys** [comment]
It's a great Idea, in the next days i will improve the style
