### ISSUE TITLE
No Show Error  link with latest change

### ISSUE THREAD

**Issue by shisapian** [MarcosEllys/newman-html-report-template-verbose#5]
The other issue is closed. So adding another one.  I did not understand the change.
Now the "Show error" link does not show at all. ( I do not have failures).

Is this expected? you show the "show error" section only when there are failures.
What I pointed out is : "You can have the show error section but when you click o this we should not show  anything if no failures."

With latest change I get this. The "Show error" link itself is not there.

<img width="1436" alt="screen shot 2018-05-31 at 11 11 24 am" src="https://user-images.githubusercontent.com/20493575/40799803-67484120-64c3-11e8-9d1d-26e20013e08f.png">

**Comment by MarcosEllys** [comment]
Yeah, i was testing to hide "Show errors" when no errors in the test, but without button it got weird.

I go to add again show errors removing the condition temporarily.

**Comment by MarcosEllys** [comment]
See now

**Comment by shisapian** [comment]
Much better .. now with number 👍
